swagger: "2.0"
info:
    title: Inventory Service
    description: HTTP service to interact with inventory bounded context
    version: ""
host: localhost:8088
basePath: api/inventory/vehicles
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/inventory/vehicles/cars:
        post:
            tags:
                - car
            summary: create car
            operationId: car#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CarCreateRequestBody'
                    required:
                        - id
                        - vin
                        - color
            responses:
                "201":
                    description: Created response.
                "400":
                    description: Bad Request response.
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/CarCreateConflictResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/CarCreateInternalResponseBody'
            schemes:
                - http
    /api/inventory/vehicles/cars/{id}:
        get:
            tags:
                - car
            summary: get car
            operationId: car#get
            parameters:
                - name: id
                  in: path
                  description: Car id in uuid format
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CarGetOKResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/CarGetBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/CarGetNotFoundResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/CarGetInternalResponseBody'
            schemes:
                - http
definitions:
    CarCreateConflictResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: create_conflict_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CarCreateInternalResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: create_internal_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CarCreateRequestBody:
        title: CarCreateRequestBody
        type: object
        properties:
            color:
                type: string
                description: Car color
                example: Vel quis aliquam et quia.
            id:
                type: string
                description: Car id in uuid format
                example: c2e05582-9040-11ee-ae47-9a5c7f2ee299
                format: uuid
            vin:
                type: string
                example: Sed ut velit corporis et tenetur.
        example:
            color: Quis non doloremque vero inventore ut et.
            id: c2e05672-9040-11ee-ae47-9a5c7f2ee299
            vin: Distinctio autem atque voluptatibus officia.
        required:
            - id
            - vin
            - color
    CarGetBadRequestResponseBody:
        title: 'Mediatype identifier: inventory.vehicle.car; view=default'
        type: object
        properties:
            color:
                type: string
                example: Distinctio quas dolores totam in.
            createdAt:
                type: string
                example: "1988-01-28T03:12:18Z"
                format: date-time
            id:
                type: string
                example: c2e0602c-9040-11ee-ae47-9a5c7f2ee299
                format: uuid
            updatedAt:
                type: string
                example: "1971-10-25T21:18:45Z"
                format: date-time
            vinData:
                $ref: '#/definitions/VinDataResponseBody'
        description: GetBad RequestResponseBody result type (default view)
        example:
            color: Tenetur consequatur illum.
            createdAt: "2013-11-21T04:03:58Z"
            id: c2e062de-9040-11ee-ae47-9a5c7f2ee299
            updatedAt: "1983-12-25T00:39:41Z"
            vinData:
                SN: Modi ipsum ipsum iusto in molestiae.
                assemblyPlant: Neque maxime quaerat similique et iure.
                brand: Debitis et fugit.
                country: Iure dolorum fugit unde vel iure pariatur.
                engineSize: Consectetur maxime ut aut asperiores.
                fuelType: Quo reprehenderit fugit rem.
                manufacturer: Quae qui vitae.
                model: Minus illum velit ad.
                vin: Voluptas vel veritatis sunt corrupti corrupti perspiciatis.
                year: Quibusdam illum quia ratione repellendus qui nihil.
        required:
            - id
            - createdAt
            - updatedAt
            - color
            - vinData
    CarGetInternalResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: get_internal_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CarGetNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: get_notFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CarGetOKResponseBody:
        title: 'Mediatype identifier: inventory.vehicle.car; view=default'
        type: object
        properties:
            color:
                type: string
                example: Cumque asperiores.
            createdAt:
                type: string
                example: "1977-04-07T02:40:10Z"
                format: date-time
            id:
                type: string
                example: c2e058de-9040-11ee-ae47-9a5c7f2ee299
                format: uuid
            updatedAt:
                type: string
                example: "1970-12-13T01:16:10Z"
                format: date-time
            vinData:
                $ref: '#/definitions/VinDataResponseBody'
        description: GetOKResponseBody result type (default view)
        example:
            color: Sit error optio illum quia reprehenderit in.
            createdAt: "1996-06-08T02:06:11Z"
            id: c2e05c58-9040-11ee-ae47-9a5c7f2ee299
            updatedAt: "1976-08-06T04:17:17Z"
            vinData:
                SN: Modi ipsum ipsum iusto in molestiae.
                assemblyPlant: Neque maxime quaerat similique et iure.
                brand: Debitis et fugit.
                country: Iure dolorum fugit unde vel iure pariatur.
                engineSize: Consectetur maxime ut aut asperiores.
                fuelType: Quo reprehenderit fugit rem.
                manufacturer: Quae qui vitae.
                model: Minus illum velit ad.
                vin: Voluptas vel veritatis sunt corrupti corrupti perspiciatis.
                year: Quibusdam illum quia ratione repellendus qui nihil.
        required:
            - id
            - createdAt
            - updatedAt
            - color
            - vinData
    VinDataResponseBody:
        title: 'Mediatype identifier: vin_data; view=default'
        type: object
        properties:
            SN:
                type: string
                example: Necessitatibus voluptates.
            assemblyPlant:
                type: string
                example: Qui sequi.
            brand:
                type: string
                example: Asperiores fugit quo adipisci id minus.
            country:
                type: string
                example: Quibusdam alias quia.
            engineSize:
                type: string
                example: Magnam illo.
            fuelType:
                type: string
                example: Sed enim.
            manufacturer:
                type: string
                example: Ducimus officia recusandae voluptatem necessitatibus.
            model:
                type: string
                example: Nostrum qui assumenda.
            vin:
                type: string
                example: Voluptas eveniet.
            year:
                type: string
                example: Quos enim sit.
        description: decoded vin data (default view)
        example:
            SN: Iste quia molestiae.
            assemblyPlant: Debitis vero quia.
            brand: Commodi totam et laudantium quos.
            country: Quidem atque cumque autem et reprehenderit.
            engineSize: Occaecati harum autem fuga nam.
            fuelType: Eum rem voluptatum ipsum alias iusto non.
            manufacturer: Placeat vel repudiandae voluptatem libero id.
            model: Voluptas quaerat aut temporibus voluptatum aut aut.
            vin: Dolorem voluptatem id quod.
            year: Accusantium quis et minima perspiciatis ab.
        required:
            - vin
